# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a5506ece42eb4aea5e13ceca54d6c349ea89c40fff5e6b5c6ff67c1d3e9b64b973c447a3090112b46b2003148a68dd9d70fa8be4396e719aea51c337126b641

test:
  secret_key_base: b90714582ae437ccd821bcbdb0a12b9b636def9c13709162100da520204d7395fc524532bfa5ff95acac2eaef50de43f6c5b8096821bafae258644871e1ee9d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
